In [414]:
import numpy as np
import pandas as pd
import os

In [415]:
dir(pd) # to see all functions in pandas

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annota

In [416]:
files = os.listdir('hepsiemlak') # to list all files in the 'hepsiemlak' directory
df = pd.concat([pd.read_csv(f"hepsiemlak/{file}") for file in files], ignore_index=True) # to read each CSV file into a pandas DataFrame and concatenate them into a single DataFrame, using a list comprehension to iterate over the sorted list of files and an f-string to construct the file path

In [417]:
print(df.info()) # to get a concise summary of the DataFrame, including the number of non-null entries and data types of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 22 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   img-link href                        9925 non-null   object 
 1   photo-count                          9902 non-null   float64
 2   list-view-price                      9925 non-null   object 
 3   list-view-date                       9791 non-null   object 
 4   list-view-title                      23 non-null     object 
 5   left                                 9925 non-null   object 
 6   celly                                9925 non-null   object 
 7   celly 2                              9925 non-null   object 
 8   celly 3                              9925 non-null   object 
 9   celly 4                              9712 non-null   object 
 10  list-view-location                   9925 non-null   object 
 11  img-wrp href                  

In [418]:
df.shape

(9925, 22)

In [419]:
df.head()

,img-link href,photo-count,list-view-price,list-view-date,list-view-title,left,celly,celly 2,celly 3,celly 4,...,he-lazy-image src,img-wrp href 2,he-lazy-image src 2,listing-card--owner-info__firm-name,listing-card--owner-info__name,he-icon href,text-ellipsis,he-lazy-image src 3,list-view-header,wp-btn
0,https://www.hepsiemlak.com/istanbul-sisli-merk...,60.0,27.0,07-03-2026,Şişli Merkez'de Eşyalı Kiralık 1+0 Stüdyo Dair...,Kiralık Daire,Stüdyo,39 m²,39\n Yaşında,Bahçe Katı,...,https://hecdnnw.hemlak.com/mncropresize/77/67/...,https://www.hepsiemlak.com/emlak-ofisi/akyildi...,https://hecdnnw.hemlak.com/mncropresize/77/67/...,Akyıldız Emlak,Özcan\n Ak,NaN,NaN,NaN,NaN,NaN
1,https://www.hepsiemlak.com/istanbul-kadikoy-ko...,17.0,85.0,07-03-2026,Kadıköy Şenesenevlerde Minübüs Caddesi Üzerin...,Kiralık Daire,3 +\n 1,110 m²,3\n Yaşında,1. Kat,...,https://hecdnnw.hemlak.com/mncropresize/77/67/...,NaN,NaN,Emlak Park Real Estate,NaN,[object Object],Hepsiemlak’ta Yeni Üye,NaN,NaN,NaN
2,https://www.hepsiemlak.com/istanbul-kadikoy-ca...,47.0,590.0,05-03-2026,Caddebostan Yalı Parselinde Deniz Manzaralı 26...,Kiralık Daire,5 +\n 1,300 m²,Sıfır Bina,1. Kat,...,https://hecdnnw.hemlak.com/mncropresize/77/67/...,https://www.hepsiemlak.com/emlak-ofisi/coldwel...,https://hecdnnw.hemlak.com/mncropresize/77/67/...,Coldwell Banker Trio,Ela Tomris\n İlkgelen,NaN,NaN,NaN,NaN,NaN
3,https://www.hepsiemlak.com/istanbul-pendik-yen...,37.0,42.5,06-03-2026,Emlak Park'tan Helenium Wings'de Full Eşyalı 2+1,Kiralık Daire,2 +\n 1,90 m²,8\n Yaşında,1. Kat,...,https://www.hepsiemlak.com/_nuxt/8cafc93fb5c74...,NaN,https://www.hepsiemlak.com/_nuxt/8cafc93fb5c74...,Emlak Park Real Estate,NaN,[object Object],Hepsiemlak’ta Yeni Üye,NaN,NaN,NaN
4,https://www.hepsiemlak.com/istanbul-bahcelievl...,6.0,35.0,06-03-2026,Çamur'dan Prime İstanbul Projesinde 1+0 Full E...,Kiralık Residence,Stüdyo,74 m²,4\n Yaşında,8. Kat,...,https://www.hepsiemlak.com/_nuxt/8cafc93fb5c74...,https://www.hepsiemlak.com/emlak-ofisi/camur-g...,https://www.hepsiemlak.com/_nuxt/8cafc93fb5c74...,Çamur Gayrimenkul,Çamur\n Gayrimenkul,[object Object],Hepsiemlak’ta Yeni Üye,https://www.hepsiemlak.com/_nuxt/8cafc93fb5c74...,NaN,NaN


In [420]:
df = df.drop(columns=['img-link href','photo-count','list-view-date','left','he-lazy-image src','img-wrp href 2','he-lazy-image src 2','listing-card--owner-info__firm-name','listing-card--owner-info__name','listing-card--owner-info__name','he-icon href','text-ellipsis','he-lazy-image src 3','list-view-header','wp-btn']) 

In [421]:
df.head()

,list-view-price,list-view-title,celly,celly 2,celly 3,celly 4,list-view-location,img-wrp href
0,27.0,Şişli Merkez'de Eşyalı Kiralık 1+0 Stüdyo Dair...,Stüdyo,39 m²,39\n Yaşında,Bahçe Katı,İstanbul / Şişli / Merkez Mah.,https://www.hepsiemlak.com/emlak-ofisi/akyildi...
1,85.0,Kadıköy Şenesenevlerde Minübüs Caddesi Üzerin...,3 +\n 1,110 m²,3\n Yaşında,1. Kat,İstanbul / Kadıköy / Kozyatağı Mah.,https://www.hepsiemlak.com/emlak-ofisi/emlak-p...
2,590.0,Caddebostan Yalı Parselinde Deniz Manzaralı 26...,5 +\n 1,300 m²,Sıfır Bina,1. Kat,İstanbul / Kadıköy / Caddebostan Mah.,https://www.hepsiemlak.com/emlak-ofisi/coldwel...
3,42.5,Emlak Park'tan Helenium Wings'de Full Eşyalı 2+1,2 +\n 1,90 m²,8\n Yaşında,1. Kat,İstanbul / Pendik / Yenişehir Mah.,https://www.hepsiemlak.com/emlak-ofisi/emlak-p...
4,35.0,Çamur'dan Prime İstanbul Projesinde 1+0 Full E...,Stüdyo,74 m²,4\n Yaşında,8. Kat,İstanbul / Bahçelievler / Yenibosna Merkez Mah.,https://www.hepsiemlak.com/emlak-ofisi/camur-g...


In [422]:
df = df.drop(columns=['img-wrp href'])

In [423]:
df.head()

,list-view-price,list-view-title,celly,celly 2,celly 3,celly 4,list-view-location
0,27.0,Şişli Merkez'de Eşyalı Kiralık 1+0 Stüdyo Dair...,Stüdyo,39 m²,39\n Yaşında,Bahçe Katı,İstanbul / Şişli / Merkez Mah.
1,85.0,Kadıköy Şenesenevlerde Minübüs Caddesi Üzerin...,3 +\n 1,110 m²,3\n Yaşında,1. Kat,İstanbul / Kadıköy / Kozyatağı Mah.
2,590.0,Caddebostan Yalı Parselinde Deniz Manzaralı 26...,5 +\n 1,300 m²,Sıfır Bina,1. Kat,İstanbul / Kadıköy / Caddebostan Mah.
3,42.5,Emlak Park'tan Helenium Wings'de Full Eşyalı 2+1,2 +\n 1,90 m²,8\n Yaşında,1. Kat,İstanbul / Pendik / Yenişehir Mah.
4,35.0,Çamur'dan Prime İstanbul Projesinde 1+0 Full E...,Stüdyo,74 m²,4\n Yaşında,8. Kat,İstanbul / Bahçelievler / Yenibosna Merkez Mah.


In [424]:
df.shape

(9925, 7)

In [425]:
df['celly'] = df['celly'].apply(lambda x: x.replace('Stüdyo','1+0')) # to replace the string 'Stüdyo' with '1+0' in the 'celly' column of the DataFrame using the apply method and a lambda function
df['celly'] = df['celly'].apply(lambda x: x.replace('\n','')) # to remove newline characters from the 'celly' column of the DataFrame using the apply method and a lambda function that replaces '\n ' and '\n' with an empty string
df['room'] = df['celly'].apply(lambda x: x.split('+')[0]).astype(int) # preparing df['room'] column;split function is used to datas with character we've choosed (for example "+"),astype is used to determine the variable type
df['living_room'] = df['celly'].apply(lambda x: x.split('+')[1]).astype(int) # and [0] and [1] means the variable will read 0.character after "+",or 1.character,whatever we choose


In [426]:
df['room'].unique() # we will try to find outliders

array([ 1,  3,  5,  2,  4,  6,  7,  9,  8, 13, 10, 12, 30, 15, 50, 16])

In [427]:
df['living_room'].unique() # find the outliders

array([  0,   1,   2,   3,   4,  13,  10, 140,   5,   7])

In [428]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   list-view-price     9925 non-null   object
 1   list-view-title     23 non-null     object
 2   celly               9925 non-null   object
 3   celly 2             9925 non-null   object
 4   celly 3             9925 non-null   object
 5   celly 4             9712 non-null   object
 6   list-view-location  9925 non-null   object
 7   room                9925 non-null   int32 
 8   living_room         9925 non-null   int32 
dtypes: int32(2), object(7)
memory usage: 620.4+ KB


In [429]:
df = df.drop(columns=['celly']) # we dont need celly column anymore
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   list-view-price     9925 non-null   object
 1   list-view-title     23 non-null     object
 2   celly 2             9925 non-null   object
 3   celly 3             9925 non-null   object
 4   celly 4             9712 non-null   object
 5   list-view-location  9925 non-null   object
 6   room                9925 non-null   int32 
 7   living_room         9925 non-null   int32 
dtypes: int32(2), object(6)
memory usage: 542.9+ KB


In [430]:
df.head()

,list-view-price,list-view-title,celly 2,celly 3,celly 4,list-view-location,room,living_room
0,27.0,Şişli Merkez'de Eşyalı Kiralık 1+0 Stüdyo Dair...,39 m²,39\n Yaşında,Bahçe Katı,İstanbul / Şişli / Merkez Mah.,1,0
1,85.0,Kadıköy Şenesenevlerde Minübüs Caddesi Üzerin...,110 m²,3\n Yaşında,1. Kat,İstanbul / Kadıköy / Kozyatağı Mah.,3,1
2,590.0,Caddebostan Yalı Parselinde Deniz Manzaralı 26...,300 m²,Sıfır Bina,1. Kat,İstanbul / Kadıköy / Caddebostan Mah.,5,1
3,42.5,Emlak Park'tan Helenium Wings'de Full Eşyalı 2+1,90 m²,8\n Yaşında,1. Kat,İstanbul / Pendik / Yenişehir Mah.,2,1
4,35.0,Çamur'dan Prime İstanbul Projesinde 1+0 Full E...,74 m²,4\n Yaşında,8. Kat,İstanbul / Bahçelievler / Yenibosna Merkez Mah.,1,0


In [431]:
df['celly 2'].unique()

array(['39 m²', '110 m²', '300 m²', '90 m²', '74 m²', '85 m²', '240 m²',
       '112 m²', '87 m²', '70 m²', '120 m²', '75 m²', '170 m²', '80 m²',
       '55 m²', '160 m²', '60 m²', '178 m²', '105 m²', '45 m²', '100 m²',
       '150 m²', '95 m²', '197 m²', '520 m²', '210 m²', '65 m²', '130 m²',
       '320 m²', '550 m²', '225 m²', '145 m²', '25 m²', '78 m²', '162 m²',
       '1.100 m²', '140 m²', '115 m²', '135 m²', '165 m²', '180 m²',
       '125 m²', '109 m²', '155 m²', '47 m²', '500 m²', '50 m²', '220 m²',
       '146 m²', '169 m²', '107 m²', '280 m²', '138 m²', '700 m²',
       '40 m²', '175 m²', '76 m²', '600 m²', '96 m²', '79 m²', '250 m²',
       '101 m²', '67 m²', '77 m²', '106 m²', '230 m²', '73 m²', '35 m²',
       '134 m²', '400 m²', '650 m²', '68 m²', '98 m²', '200 m²', '82 m²',
       '270 m²', '124 m²', '126 m²', '61 m²', '37 m²', '185 m²', '186 m²',
       '189 m²', '116 m²', '206 m²', '117 m²', '149 m²', '92 m²',
       '350 m²', '215 m²', '190 m²', '141 m²', '153 m²', '

In [432]:
df['celly 2'] =  df['celly 2'].apply(lambda x: x.replace('.','')) # we will replace . with space
df['celly 2'] =  df['celly 2'].apply(lambda x: x.replace(' m²','')).astype(int) # we will delete m2 and we will convert strings to int 


In [433]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   list-view-price     9925 non-null   object
 1   list-view-title     23 non-null     object
 2   celly 2             9925 non-null   int32 
 3   celly 3             9925 non-null   object
 4   celly 4             9712 non-null   object
 5   list-view-location  9925 non-null   object
 6   room                9925 non-null   int32 
 7   living_room         9925 non-null   int32 
dtypes: int32(3), object(5)
memory usage: 504.1+ KB


In [434]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [435]:
df.rename(columns={'celly 2': 'area'}, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   list-view-price     9925 non-null   object
 1   list-view-title     23 non-null     object
 2   area                9925 non-null   int32 
 3   celly 3             9925 non-null   object
 4   celly 4             9712 non-null   object
 5   list-view-location  9925 non-null   object
 6   room                9925 non-null   int32 
 7   living_room         9925 non-null   int32 
dtypes: int32(3), object(5)
memory usage: 504.1+ KB


In [436]:
df.head()

,list-view-price,list-view-title,area,celly 3,celly 4,list-view-location,room,living_room
0,27.0,Şişli Merkez'de Eşyalı Kiralık 1+0 Stüdyo Dair...,39,39\n Yaşında,Bahçe Katı,İstanbul / Şişli / Merkez Mah.,1,0
1,85.0,Kadıköy Şenesenevlerde Minübüs Caddesi Üzerin...,110,3\n Yaşında,1. Kat,İstanbul / Kadıköy / Kozyatağı Mah.,3,1
2,590.0,Caddebostan Yalı Parselinde Deniz Manzaralı 26...,300,Sıfır Bina,1. Kat,İstanbul / Kadıköy / Caddebostan Mah.,5,1
3,42.5,Emlak Park'tan Helenium Wings'de Full Eşyalı 2+1,90,8\n Yaşında,1. Kat,İstanbul / Pendik / Yenişehir Mah.,2,1
4,35.0,Çamur'dan Prime İstanbul Projesinde 1+0 Full E...,74,4\n Yaşında,8. Kat,İstanbul / Bahçelievler / Yenibosna Merkez Mah.,1,0


In [437]:
df['list-view-price'].unique()

array([27.0, 85.0, 590.0, 42.5, 35.0, 45.0, 125.0, 110.0, 250.0, 28.5,
       72.0, 80.0, 50.0, 95.0, 22.0, 23.0, 38.0, 55.0, 29.0, 17.5, 60.0,
       15.0, 18.0, 32.0, 160.0, 59.5, 52.0, 200.0, 51.0, 43.0, 120.0,
       31.0, 30.0, 21.5, '125.000', '39.500', '120.000', '129.000',
       '28.000', '435.000', '46.000', '22.000', '95.000', '32.500',
       '13.500', '55.000', '23.000', '18.000', '75.000', '82.000',
       '45.000', '260.000', '27.000', '35.000', '40.000', '25.000',
       '39.000', '20.000', '51.000', '32.000', '30.000', '13.000',
       '27.500', '68.000', '37.900', '15.000', '12.500', '19.000',
       '22.500', '9.500', '90.000', '85.000', '33.500', '36.000',
       '30.500', '33.000', '9.750.000', '65.000', '25.500', '12.000',
       '17.000', '80.000', '700.000', '34.500', '26.500', '24.000',
       '240.000', '50.000', '100.000', '70.000', '60.000', '36.250',
       '16.750', '20.500', '575.000', '150.000', '42.000', '26.000',
       '37.000', '81.000', '140.000', '

In [438]:
df['celly 3'].unique()

array(['39\n                        Yaşında',
       '3\n                        Yaşında', 'Sıfır Bina',
       '8\n                        Yaşında',
       '4\n                        Yaşında',
       '50\n                        Yaşında',
       '30\n                        Yaşında',
       '11\n                        Yaşında',
       '32\n                        Yaşında',
       '40\n                        Yaşında',
       '17\n                        Yaşında',
       '6\n                        Yaşında',
       '16\n                        Yaşında',
       '12\n                        Yaşında',
       '35\n                        Yaşında',
       '28\n                        Yaşında',
       '20\n                        Yaşında',
       '10\n                        Yaşında',
       '31\n                        Yaşında',
       '5\n                        Yaşında',
       '21\n                        Yaşında',
       '33\n                        Yaşında',
       '29\n             

In [439]:
df['celly 3'] = df['celly 3'].apply(lambda x: x.replace ('Sıfır Bina','0')) # we will replace "Sıfır Bina" with 0
df['celly 3'] = df['celly 3'].apply(lambda x: x.replace ('\n',''))
df['age'] = df['celly 3'].apply(lambda x: x.split(' ')[0]).astype(int) # we will split the data with space and we will take the first character and convert it to int

In [440]:
df['age'].unique()

array([ 39,   3,   0,   8,   4,  50,  30,  11,  32,  40,  17,   6,  16,
        12,  35,  28,  20,  10,  31,   5,  21,  33,  29,  15,   7,   1,
        25,  22,  18,   9,  45,  55,  13, 110,  41,  19,  49,  26,  42,
        60,   2,  14,  24,  27,  23,  34,  38,  65,  43,  56,  90,  75,
        70, 633,  37,  80,  95,  44, 100,  47, 156,  99,  36,  48,  51,
        46,  97,  88,  52,  57,  66,  54, 120,  94, 106, 199, 119])

In [441]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   list-view-price     9925 non-null   object
 1   list-view-title     23 non-null     object
 2   area                9925 non-null   int32 
 3   celly 3             9925 non-null   object
 4   celly 4             9712 non-null   object
 5   list-view-location  9925 non-null   object
 6   room                9925 non-null   int32 
 7   living_room         9925 non-null   int32 
 8   age                 9925 non-null   int32 
dtypes: int32(4), object(5)
memory usage: 542.9+ KB


In [442]:
df.drop(columns=['celly 3'], inplace=True) # we will drop celly 3 column because we have age column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9925 entries, 0 to 9924
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   list-view-price     9925 non-null   object
 1   list-view-title     23 non-null     object
 2   area                9925 non-null   int32 
 3   celly 4             9712 non-null   object
 4   list-view-location  9925 non-null   object
 5   room                9925 non-null   int32 
 6   living_room         9925 non-null   int32 
 7   age                 9925 non-null   int32 
dtypes: int32(4), object(4)
memory usage: 465.4+ KB


In [443]:
df['celly 4'].unique()

array(['Bahçe Katı', '1. Kat', '8. Kat', 'Ara Kat', nan, '4. Kat',
       '2. Kat', '10. Kat', '5. Kat', '3. Kat', 'Yüksek Giriş', 'Kot 1',
       '6. Kat', 'Teras Katı', '12. Kat', '18. Kat', '14. Kat',
       'Giriş Katı', '11. Kat', '7. Kat', '9. Kat', 'En Üst Kat',
       'Çatı Katı', '21 ve üzeri', '19. Kat', '17. Kat', '15. Kat',
       'Kot 3', '20. Kat', 'Zemin', '16. Kat', 'Yarı Bodrum',
       'Villa Katı', 'Kot 2', '13. Kat', 'Bodrum', 'Bodrum ve Zemin',
       'Tripleks'], dtype=object)

In [444]:
replace_dict = {
    'Kot 3': '-3.Kat',
    'Kot 2': '-2.Kat',
    'Kot 1': '-1.Kat',
    'Zemin': '0.Kat',
    'Bahçe Katı': '0.Kat',
    'Yüksek Giriş': '1.Kat',
    'Giriş Katı': '0.Kat',
    'Ara Kat': '3.Kat',
    'Teras Katı': '5.Kat',
    'En Üst Kat': '5.Kat',
    'Çatı Katı': '6.Kat',
    '21 ve üzeri': '21.Kat',
    'Yarı Bodrum': '0.Kat',
    'Villa Katı': '0.Kat',
    'Bodrum': '-1.Kat',
    'Bodrum ve Zemin': '-1.Kat',
    'Tripleks': '3.Kat',
    'nan': '2.Kat'
}

In [445]:
df['celly 4'] = df['celly 4'].replace(replace_dict.keys(), replace_dict.values()) # we will replace the values in celly 4 column with the values in replace_dict
print(df['celly 4'].unique())

['0.Kat' '1. Kat' '8. Kat' '3.Kat' nan '4. Kat' '2. Kat' '10. Kat'
 '5. Kat' '3. Kat' '1.Kat' '-1.Kat' '6. Kat' '5.Kat' '12. Kat' '18. Kat'
 '14. Kat' '11. Kat' '7. Kat' '9. Kat' '6.Kat' '21.Kat' '19. Kat'
 '17. Kat' '15. Kat' '-3.Kat' '20. Kat' '16. Kat' '-2.Kat' '13. Kat']


In [446]:
print(df['celly 4'].unique())

['0.Kat' '1. Kat' '8. Kat' '3.Kat' nan '4. Kat' '2. Kat' '10. Kat'
 '5. Kat' '3. Kat' '1.Kat' '-1.Kat' '6. Kat' '5.Kat' '12. Kat' '18. Kat'
 '14. Kat' '11. Kat' '7. Kat' '9. Kat' '6.Kat' '21.Kat' '19. Kat'
 '17. Kat' '15. Kat' '-3.Kat' '20. Kat' '16. Kat' '-2.Kat' '13. Kat']


In [447]:
df = df.dropna(subset=['celly 4'])

In [448]:
df['floor'] = df['celly 4'].apply(lambda x: x.split('.')[0]).astype(int) 
 # we will drop the rows with NaN values in floor column

In [449]:
df['floor'].unique()

array([ 0,  1,  8,  3,  4,  2, 10,  5, -1,  6, 12, 18, 14, 11,  7,  9, 21,
       19, 17, 15, -3, 20, 16, -2, 13])

In [450]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9712 entries, 0 to 9924
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   list-view-price     9712 non-null   object
 1   list-view-title     21 non-null     object
 2   area                9712 non-null   int32 
 3   celly 4             9712 non-null   object
 4   list-view-location  9712 non-null   object
 5   room                9712 non-null   int32 
 6   living_room         9712 non-null   int32 
 7   age                 9712 non-null   int32 
 8   floor               9712 non-null   int32 
dtypes: int32(5), object(4)
memory usage: 569.1+ KB


In [451]:
df.head()

,list-view-price,list-view-title,area,celly 4,list-view-location,room,living_room,age,floor
0,27.0,Şişli Merkez'de Eşyalı Kiralık 1+0 Stüdyo Dair...,39,0.Kat,İstanbul / Şişli / Merkez Mah.,1,0,39,0
1,85.0,Kadıköy Şenesenevlerde Minübüs Caddesi Üzerin...,110,1. Kat,İstanbul / Kadıköy / Kozyatağı Mah.,3,1,3,1
2,590.0,Caddebostan Yalı Parselinde Deniz Manzaralı 26...,300,1. Kat,İstanbul / Kadıköy / Caddebostan Mah.,5,1,0,1
3,42.5,Emlak Park'tan Helenium Wings'de Full Eşyalı 2+1,90,1. Kat,İstanbul / Pendik / Yenişehir Mah.,2,1,8,1
4,35.0,Çamur'dan Prime İstanbul Projesinde 1+0 Full E...,74,8. Kat,İstanbul / Bahçelievler / Yenibosna Merkez Mah.,1,0,4,8


In [452]:
df = df.drop(columns=['celly 4','list-view-title']) 

In [453]:
df.head()

,list-view-price,area,list-view-location,room,living_room,age,floor
0,27.0,39,İstanbul / Şişli / Merkez Mah.,1,0,39,0
1,85.0,110,İstanbul / Kadıköy / Kozyatağı Mah.,3,1,3,1
2,590.0,300,İstanbul / Kadıköy / Caddebostan Mah.,5,1,0,1
3,42.5,90,İstanbul / Pendik / Yenişehir Mah.,2,1,8,1
4,35.0,74,İstanbul / Bahçelievler / Yenibosna Merkez Mah.,1,0,4,8


In [454]:
df['list-view-location'].head()

0                     İstanbul / Şişli / Merkez Mah.
1                İstanbul / Kadıköy / Kozyatağı Mah.
2              İstanbul / Kadıköy / Caddebostan Mah.
3                 İstanbul / Pendik / Yenişehir Mah.
4    İstanbul / Bahçelievler / Yenibosna Merkez Mah.
Name: list-view-location, dtype: object

In [455]:
new_cols = df['list-view-location'].str.split('/', expand=True)


df['city'] = new_cols[0].str.strip()
df['district'] = new_cols[1].str.strip()
df['neighbourhood'] = new_cols[2].str.strip()


print(df[['city', 'district', 'neighbourhood']].tail(50))

          city      district          neighbourhood
9871  İstanbul       Maltepe         Küçükyalı Mah.
9872  İstanbul         Şişli      Halaskargazi Mah.
9873  İstanbul      Ümraniye        Dumlupınar Mah.
9874  İstanbul         Şişli             Fulya Mah.
9875  İstanbul        Kartal         Orhantepe Mah.
9876  İstanbul   Sultanbeyli         Orhangazi Mah.
9877  İstanbul  Küçükçekmece             Fatih Mah.
9878  İstanbul      Esenyurt           Mevlana Mah.
9879  İstanbul       Maltepe             Çınar Mah.
9880  İstanbul      Esenyurt           Atatürk Mah.
9881  İstanbul     Kağıthane          Hamidiye Mah.
9882  İstanbul         Tuzla           Aydınlı Mah.
9883  İstanbul      Bağcılar         Mahmutbey Mah.
9884  İstanbul          Şile           Balibey Mah.
9885  İstanbul        Beykoz           Yalıköy Mah.
9886  İstanbul       Silivri              Yeni Mah.
9887  İstanbul    Sancaktepe     Veysel Karani Mah.
9888  İstanbul        Pendik         Yenişehir Mah.
9889  İstanb

In [456]:
# Convert Turkish characters to English and make them lowercase
def convert_to_english(text):
    if pd.isnull(text):
        return text
    char_map = {
        'ç': 'c', 'ğ': 'g', 'ı': 'i', 'İ': 'i', 'ö': 'o', 'ş': 's', 'ü': 'u',
        'Ç': 'c', 'Ğ': 'g', 'Ö': 'o', 'Ş': 's', 'Ü': 'u'
    }
    for tr_char, en_char in char_map.items():
        text = text.replace(tr_char, en_char)
    return text.lower() # Lower function

# Apply columns to this function
target_cols = ['city', 'district', 'neighbourhood']

for col in target_cols:
    # Apply the conversion function to each column
    df[col] = df[col].apply(convert_to_english)



In [457]:
df['neighbourhood'] = df['neighbourhood'].str.replace(r'\s+mah.*', '', regex=True).str.strip()


print(df[['city', 'district', 'neighbourhood']].head())

       city      district     neighbourhood
0  istanbul         sisli            merkez
1  istanbul       kadikoy         kozyatagi
2  istanbul       kadikoy       caddebostan
3  istanbul        pendik         yenisehir
4  istanbul  bahcelievler  yenibosna merkez


In [458]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9712 entries, 0 to 9924
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   list-view-price     9712 non-null   object
 1   area                9712 non-null   int32 
 2   list-view-location  9712 non-null   object
 3   room                9712 non-null   int32 
 4   living_room         9712 non-null   int32 
 5   age                 9712 non-null   int32 
 6   floor               9712 non-null   int32 
 7   city                9712 non-null   object
 8   district            9712 non-null   object
 9   neighbourhood       9712 non-null   object
dtypes: int32(5), object(5)
memory usage: 644.9+ KB


In [459]:
df['list-view-location'].head()

0                     İstanbul / Şişli / Merkez Mah.
1                İstanbul / Kadıköy / Kozyatağı Mah.
2              İstanbul / Kadıköy / Caddebostan Mah.
3                 İstanbul / Pendik / Yenişehir Mah.
4    İstanbul / Bahçelievler / Yenibosna Merkez Mah.
Name: list-view-location, dtype: object

In [460]:
df = df.drop(columns=['list-view-location']) 

In [461]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9712 entries, 0 to 9924
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  9712 non-null   object
 1   area             9712 non-null   int32 
 2   room             9712 non-null   int32 
 3   living_room      9712 non-null   int32 
 4   age              9712 non-null   int32 
 5   floor            9712 non-null   int32 
 6   city             9712 non-null   object
 7   district         9712 non-null   object
 8   neighbourhood    9712 non-null   object
dtypes: int32(5), object(4)
memory usage: 569.1+ KB


In [462]:
df['list-view-price'].unique()

array([27.0, 85.0, 590.0, 42.5, 35.0, 45.0, 110.0, 250.0, 28.5, 72.0,
       80.0, 50.0, 95.0, 22.0, 23.0, 38.0, 55.0, 29.0, 17.5, 60.0, 15.0,
       18.0, 32.0, 160.0, 59.5, 52.0, 51.0, 43.0, 120.0, 31.0, 30.0, 21.5,
       '125.000', '39.500', '28.000', '46.000', '22.000', '95.000',
       '32.500', '13.500', '55.000', '23.000', '18.000', '75.000',
       '82.000', '45.000', '260.000', '27.000', '35.000', '40.000',
       '25.000', '39.000', '20.000', '51.000', '32.000', '30.000',
       '13.000', '27.500', '37.900', '15.000', '12.500', '19.000',
       '22.500', '9.500', '90.000', '85.000', '33.500', '120.000',
       '36.000', '30.500', '33.000', '9.750.000', '65.000', '25.500',
       '12.000', '17.000', '80.000', '700.000', '34.500', '26.500',
       '24.000', '240.000', '50.000', '100.000', '70.000', '60.000',
       '36.250', '16.750', '20.500', '575.000', '150.000', '42.000',
       '26.000', '37.000', '81.000', '140.000', '25.020', '45.750',
       '42.500', '24.500', '38.000

In [463]:
df['list-view-price'] = df['list-view-price'].astype(str).apply(lambda x:x.replace('.','')) 
df['price'] = df['list-view-price'].astype(int) 


In [464]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9712 entries, 0 to 9924
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  9712 non-null   object
 1   area             9712 non-null   int32 
 2   room             9712 non-null   int32 
 3   living_room      9712 non-null   int32 
 4   age              9712 non-null   int32 
 5   floor            9712 non-null   int32 
 6   city             9712 non-null   object
 7   district         9712 non-null   object
 8   neighbourhood    9712 non-null   object
 9   price            9712 non-null   int32 
dtypes: int32(6), object(4)
memory usage: 607.0+ KB


In [465]:
df['price'].unique()

array([     270,      850,     5900,      425,      350,      450,
           1100,     2500,      285,      720,      800,      500,
            950,      220,      230,      380,      550,      290,
            175,      600,      150,      180,      320,     1600,
            595,      520,      510,      430,     1200,      310,
            300,      215,   125000,    39500,    28000,    46000,
          22000,    95000,    32500,    13500,    55000,    23000,
          18000,    75000,    82000,    45000,   260000,    27000,
          35000,    40000,    25000,    39000,    20000,    51000,
          32000,    30000,    13000,    27500,    37900,    15000,
          12500,    19000,    22500,     9500,    90000,    85000,
          33500,   120000,    36000,    30500,    33000,  9750000,
          65000,    25500,    12000,    17000,    80000,   700000,
          34500,    26500,    24000,   240000,    50000,   100000,
          70000,    60000,    36250,    16750,    20500,   575

In [466]:
df.drop(df[df['price'] < 2500].index, inplace=True)
df['price'].unique()

array([    5900,     2500,   125000,    39500,    28000,    46000,
          22000,    95000,    32500,    13500,    55000,    23000,
          18000,    75000,    82000,    45000,   260000,    27000,
          35000,    40000,    25000,    39000,    20000,    51000,
          32000,    30000,    13000,    27500,    37900,    15000,
          12500,    19000,    22500,     9500,    90000,    85000,
          33500,   120000,    36000,    30500,    33000,  9750000,
          65000,    25500,    12000,    17000,    80000,   700000,
          34500,    26500,    24000,   240000,    50000,   100000,
          70000,    60000,    36250,    16750,    20500,   575000,
         150000,    42000,    26000,    37000,    81000,   140000,
          25020,    45750,    42500,    24500,    38000,    21500,
          17500,    57000,    34000,   175000,    28250,    67000,
         290000,   650000,    52000,    49000,    11000,   195000,
          40250,    57500,    37500,    69000,   110000,   375

In [467]:
df = df.drop(columns=['list-view-price']) 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7727 entries, 2 to 9924
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   area           7727 non-null   int32 
 1   room           7727 non-null   int32 
 2   living_room    7727 non-null   int32 
 3   age            7727 non-null   int32 
 4   floor          7727 non-null   int32 
 5   city           7727 non-null   object
 6   district       7727 non-null   object
 7   neighbourhood  7727 non-null   object
 8   price          7727 non-null   int32 
dtypes: int32(6), object(3)
memory usage: 422.6+ KB


In [468]:
df.to_csv('cleaned_data.csv', index=False)